config/routes.rb
SecondChance::Application.routes.draw do
  
  # NOTE: We are using different controller names for our members resource.  "sessions" and "registrations" are being used by 
  # the refinerycms user resource.  We are using the members resource to track our non-cms users - the foster and volunteer people 
  # who will use the website.  The routes for the user resource happen auto-magically via the refinerycms gem.
  devise_for :members, :controllers => { :sessions => "login", :registrations => "signup" }

  resources :dog_photos
  resources :dogs do
    collection { post :import_dog_data }
  end
    
  # match '/adoption_application' => 'dog_application_instances#new'
  # resources :dog_application_instances

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_content_page.html.erb
<%
  # provide a default array for collecting CSS for sections
  css = []

  # if 'sections' is passed in as a local_assigns, all of this is ignored.
  if local_assigns[:sections].blank?
    # always have a title unless specified to be false
    sections = []
    unless (local_assigns[:title] == false)
      sections = [{:yield => :body_content_title, :fallback => page_title, :title => true}]
    end

    # append sections from this page.
    @page.parts.inject(sections) do |s, part|
      # we have some default yields, body_content_left and body_content_right
      # these map to 'body' and 'side_body' fields in default Refinery.
      section = {:fallback => part.body}
      section[:yield] = case (title_symbol = part.title.to_s.gsub(/\ /, '').underscore.to_sym)
        when :body then :body_content_left
        when :side_body then :body_content_right
        else title_symbol
        end

      # add section to the list unless we were specifically requested not to.
      # otherwise, add css saying it's been removed.
      unless (local_assigns[:hide_sections]||=[]).include?(section[:yield])
        s << section
      else
        css << "no_#{section[:yield]}"
      end
    end unless @page.nil? or @page.parts.blank?

    # Ensure that even without @page.parts we still have body_content_left and body_content_right
    all_yields = sections.collect{|s| s[:yield]}
    sections << {:yield => :body_content_left} unless all_yields.include?(:body_content_left)
    sections << {:yield => :body_content_right} unless all_yields.include?(:body_content_right)
  end

  # you can add more sections to the list using something like this:
  # sections |= [{:yield => :something_else, :fallback => another_method, :id => 'something'}]

  sections.each do |section|
    section[:html] = yield(section[:yield]) if section[:yield].present?

    if section[:html].blank? and !local_assigns[:show_empty_sections] and
       !local_assigns[:remove_automatic_sections] and section.keys.include?(:fallback) and
       section[:fallback].present?
      section[:html] = raw(section[:fallback])
    end

    dom_id = section[:id] || section[:yield]
    if section[:html].present?
      if section[:title]
        section[:html] = "<h1 id='#{dom_id}'>#{section[:html]}</h1>".html_safe
      else
        section[:html] = "<section id='#{dom_id}'><div class='inner'>#{section[:html]}</div></section>".html_safe
      end
    else
      css << "no_#{dom_id}"
    end
  end
-%>
<section id='body_content'<%= " class='#{css.join(' ')}'" if css.present? %>>
  <%= raw sections.map{|section| section[:html]}.join("\n") -%>
</section>
<%= render :partial => '/shared/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/shared/_flash_messages.html.haml
-if flash[:notice]
  .alert-message.success
    %p
      =flash[:notice]

-if flash[:alert]
  .alert-message.error
    %p
      =flash[:alert]

-if flash[:error]
  .alert-message.error
    %p
      =flash[:error]

app/views/shared/_head.html.haml
%head
  %meta{:charset => ::Refinery::Application.config.encoding}
  %meta{'http-equiv' => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
  %title= browser_title(yield(:title))
  -if @meta.meta_description.present?
    %meta{:content => @meta.meta_description}
  -if @meta.meta_description.present?
    %meta{:description => @meta.meta_description}
  = csrf_meta_tag
  = yield :meta
  = stylesheet_link_tag "home" if home_page?
  = yield :stylesheets
  = render :partial => "/shared/javascripts"
  = render :partial => '/shared/google_analytics' unless local_request?
  = favicon_link_tag

app/views/shared/_javascripts.html.haml
= yield :before_javascript_libraries
= yield :javascript_libraries
= yield :after_javascript_libraries
= yield :javascripts

app/views/shared/_login_form_modal.haml
#login_form.modal.fade
  .modal-header
    %a.close{:href => "javascript:void(0)"} x
    <h3>Volunteer Log In</h3>
  = form_for Member.new, :url => member_session_path do |f|
    .clearfix
      = f.label :email
      .input
        = f.text_field :email
    .clearfix
      = f.label :password
      .input
        = f.password_field :password
    .actions
      = f.submit 'Sign In', :class => "btn primary"
  %p.span4
    %span Don't have an account?
    %br
    %span= link_to 'Sign Up for an Account', new_member_registration_path, :id => 'registration_link'